Optimization branch
hsp-iit/multi-tactile-6d-estimation pull request #2
Opened 2023-10-03 14:07 UTC by gabrielecaddeo

2023-10-09 20:55 UTC, xEnVrE requested changes
Dear @gabrielecaddeo, thank you for the contribution.

There are several changes I would like to request. Given their number, feel free to ask me about them during f2f meetings. Thank you

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +
I would add a docstring here explaining what the script does in general.

Thank you

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +            rotation_errors.append(np.linalg.norm(rotations[i, 3:]))
how are you storing the rotation matrix within `rotations[i, 3:]`? Can we document it?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +    np.savetxt("total_filtered_indexes.txt", filtered_indexes)
Do we really need all of them for subsequent steps of the pipeline?
Why don't you use, e.g., pickle to save all these matrices as single file `results.pickle` that you can re-load in python easily?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +
Can we add a small comment to describe what we are looping on?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +    for j in range(loop_range):
Can we add a small comment to describe what we are looping on?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/evaluate_poses.py
> +    np.savetxt("total_filtered_indexes.txt", filtered_indexes)
I am not seeing the `ADI-AUC` metric evaluated in this script. Is not the `evaluate_poses.py` script designed to evaluate the performance of the output poses?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
```suggestion

```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    # Save the ground truth pose. In our setup was fixed
I would maybe move the ground truth pose somewhere else, maybe in the config file, and load it from the configuration so that people can test the algorithm with a different GT, if they want, more easily.

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    save_pose(points, np.array([0.1, 0.0, 0.2, 0.0, 0.0, 0.0]), './real_pose.off')
Can we save it at the end of the script, before closing everything? So that all saves are localized in a single place. Thank you

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
```suggestion

```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    save_points_as_off(landmarks, './landmarks.off')
Can we save it at the end of the script, before closing everything? So that all saves are localized in a single place. Thank you

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    def eval_triplet(item: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float=0.005)-> jnp.bool:
I would very careful with defaults here given that you are about to `jit` these methods. Can we avoid them?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    def eval_triplet(item: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float=0.005)-> jnp.bool:
```suggestion
    def eval_ntuple(ntuple: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float=0.005)-> jnp.bool:
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +        """
```suggestion
        """
        Evaluate the n-tuple of sensors depending on the actual position of the sensors given by the proprioception.
        Return true if the n-tuple is valid, i.e. the distance between the sensors in the n-tuple is compatible with that of the sensors as given by the proprioception, false otherwise.
        
        Args:
            ntuple (jnp.array): the n-tuple containing the indexes to be used to access the array of points and obtain the corresponding 3D Cartesian position of the sensor
            points (np.array): array of all points, each to be considered as the Cartesian position of one sensor
            landmarks (np.array): positions of the sensors from the proprioception
            comb (tuple): tuple with all possible connections between N sensors
                                  For example: for three sensors ((0, 1), (0, 2), (1, 2))
            threshold (float): it decides if the n-tuple is accepted or not by comparing the difference between the mutual landmarks distance and the mutual points distance averaged across all combinations in comb

        Returns:
            jnp.bool
        """
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +        return vmap(eval_triplet, in_axes = (1, None, None, None, None))(indexes, points, landmarks, comb, threshold)
```suggestion
    def eval_ntuples(indexes: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float)-> jnp.array:
        return vmap(eval_triplet, in_axes = (1, None, None, None, None))(indexes, points, landmarks, comb, threshold)
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
```suggestion

```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    # Store the possible combinatory combinations between sensors
```suggestion
   # Evaluate all the possible combinations of N sensors
   # For example: for three sensors ((0, 1), (0, 2), (1, 2))
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
```suggestion

```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
Something wrong is going on here, probably an indentation issue, otherwise these lines would overwrite the outcome at lines 148 and 151.

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +                filtered_indexes = None
Can you add a comment for each of the branches in the if .. else? At least that would help understand what is going on here, thank you!

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +            print(filtered_indexes.shape)
```suggestion
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    def eval_item(item, points, landmarks, twist):
I would a comment with the mathematics here.

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +        return vmap(g, in_axes=(1,1))(twists, filtered_indexes)
Can we briefly comment on `in_axes(1,1)` here? It would ease a lot the task of reading this code. Thank you

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    iters = 700
Can we move this to the configuration file?
```suggestion
    iters = 700
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    # Save the time to understand how much time we need to generate the random poses
```suggestion
    # Time benchmarking
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +
```suggestion

```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    print(time.time() - start_time)
```suggestion
    print("Time required to initialize the poses: ")
    print(time.time() - start_time)
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    # Consider all around positions for the poses since the precision of the GD can depend on the starting pose.
```suggestion
    # For each given orientation, consider alternatives for the initial position around the centroid
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    positions = np.array([[0, 0, 0], [1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1], [1, 1, 1], [-1, -1, -1], [1, -1, 1], [1, -1, -1], [1, 1, -1], [-1, -1, 1],[-1, 1, 1], [-1, 1,
```suggestion
    directions = np.array([[0, 0, 0], [1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1], [1, 1, 1], [-1, -1, -1], [1, -1, 1], [1, -1, -1], [1, 1, -1], [-1, -1, 1],[-1, 1, 1], [-1, 1, -1]])
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    position_multiplier = 0.2
```suggestion
    # Use the following scaler to shift the positions along the above define directions
    position_scaler = 0.2
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +        K[3:6, 3:6] *= 1.0
Can we move the gain in the configuration file?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +        f.close()
Would not it be better to do all the evalutions for all the directions and then save them in a single pickle file, instead of having output files for each "position"?

This seems to me rather inefficient and error prone when you have to re-load the results back in an evaluation script. I would prefer having a standard Python list where for each initial condition + n-tuple combination you save the final pose (or better the history of the poses along the gradient descent).

2023-10-09 20:55 UTC, xEnVrE commented on optimization/optimization.py
> +    for position in range(positions.shape[0]):
Is it possible to run all the gradient descent iterations on all the twists without making this for cycle?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +    A class to hadle the tactile-based selection of the points.
```suggestion
    A class to handle the tactile-based selection of the points.
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        Calculate the remaining indexes.
What is the meaning of "remaining" here?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        eliminate_points = config['EliminatePoints']
What is this "eliminate points" about?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        normalization_bool = autoencoder['normalization_bool']
What is a "normalization bool"?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        # Assign the useful values
```suggestion
        # Assign some useful values
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +                print(angle_comparison_vector)
```suggestion
```

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +                f.write(str(self.point_clouds_array[j][i][0]) + " " + str(self.point_clouds_array[j][i][1]) + " " + str(self.point_clouds_array[j][i][2]) + " " + str(1.0) + " " + str(0.0) + " " + str
I would move this somewhere else as it conflicts a bit with then name of the method `calculate_indexes`.

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +                if abs(self.angles_comparison_vectors[j] - angles[i]) < 0.04:
Can `0.04` become a parameter that you load from the configuration file?

2023-10-09 20:55 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +    def calculate_database(self) -> None:
Seems you are not calling this method from nowhere, can it be maybe removed? Thank you

2023-10-10 08:01 UTC, gabrielecaddeo commented on optimization/evaluate_poses.py
> +    np.savetxt("total_filtered_indexes.txt", filtered_indexes)
no, this is for ordering the poses

2023-10-10 08:06 UTC, gabrielecaddeo commented on optimization/tactile_based_selector.py
> +    def calculate_database(self) -> None:
The calculate database method is useful to compute offline the database angles. During inference is not used because the database is already computed

2023-10-10 14:35 UTC, gabrielecaddeo commented on optimization/evaluate_poses.py
> +            rotation_errors.append(np.linalg.norm(rotations[i, 3:]))
The correct term would have been "twists". I do not know why I called them rotations now that I think about it

2023-10-10 14:59 UTC, gabrielecaddeo commented on optimization/optimization.py
> +    def eval_triplet(item: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float=0.005)-> jnp.bool:
We can, but I do not understand why you are saying that. The default value we are speaking about is a float, not an int

2023-10-10 15:05 UTC, gabrielecaddeo commented on optimization/optimization.py
> +        """
Solved, however I would not eliminate the optional value

2023-10-10 15:10 UTC, gabrielecaddeo commented on optimization/optimization.py
> +            print(filtered_indexes.shape)
In my opinion it is not bad at all seeing how the number of indexes is pruned at every computations, don't you think?

2023-10-10 15:21 UTC, gabrielecaddeo commented on optimization/optimization.py
> +    for position in range(positions.shape[0]):
In theory yes, but I do need time to implement another jax structure

2023-10-10 15:22 UTC, gabrielecaddeo commented on optimization/tactile_based_selector.py
> +        Calculate the remaining indexes.
Means the remaining indexes after the tactile-based-selection

2023-10-10 15:24 UTC, gabrielecaddeo commented on optimization/tactile_based_selector.py
> +        eliminate_points = config['EliminatePoints']
It was the field of the config file for the variables related to this script. The name can be changed

2023-10-10 15:25 UTC, gabrielecaddeo commented on optimization/tactile_based_selector.py
> +        normalization_bool = autoencoder['normalization_bool']
To see if we should normalize the image or not

2023-10-25 11:34 UTC, xEnVrE commented on optimization/optimization.py
> +            print(filtered_indexes.shape)
Ok but then please add a description of the output.

2023-10-25 11:35 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        Calculate the remaining indexes.
Can you please add a refined description in the docstring please?

2023-10-25 11:35 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        eliminate_points = config['EliminatePoints']
> The name can be changed
Can you propose an alternative?

2023-10-25 11:36 UTC, xEnVrE commented on optimization/tactile_based_selector.py
> +        normalization_bool = autoencoder['normalization_bool']
Can we name it `enable_normalization`?

2023-11-04 10:39 UTC, xEnVrE commented on optimization/optimization.py
> +    def eval_triplet(item: jnp.array, points: np.array, landmarks: np.array, comb: tuple, threshold: float=0.005)-> jnp.bool:
> The default value we are speaking about is a float, not an int

Why is that relevant?

2023-11-05 19:25 UTC, xEnVrE approved these changes
@gabrielecaddeo fine with me if you have tested it again.

Can you update the `README.md` with the correct date and also squash before merging, please?

Thank you

2023-11-13 16:38 UTC, merged